/**
 * Reads `data/theme.config.ts` and emits `app/generated-tokens.css`.
 * Runs in `predev` and `prebuild` so `globals.css` never hardcodes a color,
 * type size, or motion duration — they all trace back to one file.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { colors, type, motion, layout, radius } from '../data/theme.config'

function colorVars(theme: Record<string, string>, indent = '  ') {
  return Object.entries(theme)
    .map(([key, value]) => {
      const cssKey = key.replace(/(\d+)$/, '-$1') // ink950 -> ink-950
      return `${indent}--color-${cssKey}: ${value};`
    })
    .join('\n')
}

function typeVars() {
  return Object.entries(type.scale)
    .map(([key, v]) => {
      const cssKey = key.replace(/[A-Z]/g, (m) => `-${m.toLowerCase()}`)
      return `  --font-size-${cssKey}: ${v.size};\n  --tracking-${cssKey}: ${v.tracking};\n  --leading-${cssKey}: ${v.lh};`
    })
    .join('\n')
}

const css = `/* GENERATED by scripts/generate-tokens.ts from data/theme.config.ts. Do not edit. */

:root {
${colorVars(colors.dark)}
  /* Actual font-family names come from next/font (lib/fonts.ts), which sets
     --font-switzer / --font-geist-mono on <html>. These are just the
     fallback stacks, composed with those in globals.css. */
  --font-display-fallback: ${type.display.fallback};
  --font-mono-fallback: ${type.mono.fallback};
${typeVars()}
  --ease-resolve: ${motion.easing.resolve};
  --ease-settle: ${motion.easing.settle};
  --ease-exit: ${motion.easing.exit};
  --duration-micro: ${motion.duration.micro}ms;
  --duration-ui: ${motion.duration.ui}ms;
  --duration-reveal: ${motion.duration.reveal}ms;
  --duration-scene: ${motion.duration.scene}ms;
  --duration-hero-scene: ${motion.duration.heroScene}ms;
  --container-max: ${layout.containerMax}px;
  --content-max: ${layout.contentMax}px;
  --gutter: ${layout.gutter}px;
  --baseline: ${layout.baseline}px;
  --section-rhythm: ${layout.sectionRhythm};
  --radius-sharp: ${radius.sharp};
  --radius-soft: ${radius.soft};
}

:root[data-theme='light'] {
${colorVars(colors.light)}
}

@media (prefers-color-scheme: light) {
  :root:not([data-theme='dark']) {
${colorVars(colors.light, '    ')}
  }
}
`

const outPath = resolve(__dirname, '../app/generated-tokens.css')
mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, css)
console.log(`✓ Wrote design tokens → ${outPath}`)
